apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-coder-engine
  namespace: ai-factory-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-coder-engine
  template:
    metadata:
      labels:
        app: local-coder-engine
    spec:
      containers:
        - name: ollama
          image: docker.io/ollama/ollama:latest
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0:11434"
            - name: OLLAMA_MODELS
              value: /tmp/.ollama/models
          ports:
            - containerPort: 11434
              name: http
              protocol: TCP
